### ISSUE TITLE
Query on interpretation of unit conversion factors

### ISSUE THREAD

**Issue by jonc125** [NeurodataWithoutBorders/api-python#16]
The spec says things like "Scalar to multiply each element in data to convert it to the specified
unit" in Timeseries and its subclasses. This suggests that values stored in say millimetres should have a conversion attribute of 1000 and specify the unit as 'metre'. In /general/optophysiology the spec describes conversion as "Multiplier to get from stored values to specified unit (e.g., 1e-3 for millimeters)", where the example gives the opposite sense to the text.

Which is correct?

**Comment by keithg-alleninstitute** [comment]
Hi Jonathan,

Good catch. You first interpretation is correct. The example is in error.

All the best,
Keith

From: Jonathan Cooper
Sent: Wednesday, March 8, 2017 09:15
To: NeurodataWithoutBorders/api-python
Reply To: NeurodataWithoutBorders/api-python
Cc: Subscribed
Subject: [NeurodataWithoutBorders/api-python] Query on interpretation of unit conversion factors (#16)



The spec says things like "Scalar to multiply each element in data to convert it to the specified
unit" in Timeseries and its subclasses. This suggests that values stored in say millimetres should have a conversion attribute of 1000 and specify the unit as 'metre'. In /general/optophysiology the spec describes conversion as "Multiplier to get from stored values to specified unit (e.g., 1e-3 for millimeters)", where the example gives the opposite sense to the text.

Which is correct?
