### ISSUE TITLE
Installation instructions don't mention h5py dependency

### ISSUE THREAD

**Issue by jonc125** [NeurodataWithoutBorders/api-python#7]
They are also not explicit about whether Python 2 or 3 should be used, though I realise that's a work in progress. I'm happy to submit a PR for the docs, or indeed update setup.py to require h5py unless there is a reason this wasn't done?

**Comment by jeffteeters** [comment]
These should be fixed.  If you have time, go ahead and submit a PR for the
docs and make setup.py require h5py.
Thanks!
